SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- --------------------------------------------------------

--
-- Table structure for table `fifa_teams`
--

CREATE TABLE `fifa_teams` (
  `name` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `fifa_teams`
--

INSERT INTO `fifa_teams` (`name`) VALUES
('Afghanistan'),
('Australia'),
('Bahrain'),
('Bangladesh'),
('Bhutan'),
('Brunei Darussalam'),
('Cambodia'),
('China PR'),
('Chinese Taipei'),
('Guam'),
('Hong Kong'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Japan'),
('Jordan'),
('Korea DPR'),
('Korea Republic'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Lebanon'),
('Macau'),
('Malaysia'),
('Maldives'),
('Mongolia'),
('Myanmar'),
('Nepal'),
('Northern Mariana Islands'),
('Oman'),
('Pakistan'),
('Palestine'),
('Philippines'),
('Qatar'),
('Saudi Arabia'),
('Singapore'),
('Sri Lanka'),
('Syria'),
('Tajikistan'),
('Thailand'),
('Timor-Leste'),
('Turkmenistan'),
('United Arab Emirates'),
('Uzbekistan'),
('Vietnam'),
('Yemen'),
('Algeria'),
('Angola'),
('Benin'),
('Botswana'),
('Burkina Faso'),
('Burundi'),
('Cameroon'),
('Cape Verde'),
('Central African Republic'),
('Chad'),
('Comoros'),
('Côte d\'Ivoire'),
('Congo'),
('Congo DR'),
('Djibouti'),
('Egypt'),
('Equatorial Guinea'),
('Eritrea'),
('Ethiopia'),
('Gabon'),
('Gambia'),
('Ghana'),
('Guinea'),
('Guinea-Bissau'),
('Kenya'),
('Lesotho'),
('Liberia'),
('Libya'),
('Madagascar'),
('Malawi'),
('Mali'),
('Mauritania'),
('Mauritius'),
('Morocco'),
('Mozambique'),
('Namibia'),
('Niger'),
('Nigeria'),
('Réunion'),
('Rwanda'),
('São Tomé and Príncipe'),
('Senegal'),
('Seychelles'),
('Sierra Leone'),
('Somalia'),
('South Africa'),
('Sudan'),
('Swaziland'),
('Tanzania'),
('Togo'),
('Tunisia'),
('Uganda'),
('Zambia'),
('Zimbabwe'),
('Anguilla'),
('Antigua and Barbuda'),
('Bahamas'),
('Barbados'),
('Belize'),
('Bermuda'),
('British Virgin Islands'),
('Canada'),
('Cayman Islands'),
('Costa Rica'),
('Cuba'),
('Curaçao'),
('Dominica'),
('Dominican Republic'),
('El Salvador'),
('French Guiana'),
('Grenada'),
('Guadeloupe'),
('Guatemala'),
('Guyana'),
('Haiti'),
('Honduras'),
('Jamaica'),
('Martinique'),
('Mexico'),
('Montserrat'),
('Nicaragua'),
('Panama'),
('Puerto Rico'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint-Martin'),
('Saint Vincent and the Grenadines'),
('Sint Maarten'),
('Suriname'),
('Trinidad and Tobago'),
('Turks and Caicos Islands'),
('United States'),
('U.S. Virgin Islands'),
('Argentina'),
('Bolivia'),
('Brazil'),
('Chile'),
('Colombia'),
('Ecuador'),
('Paraguay'),
('Peru'),
('Uruguay'),
('Venezuela'),
('American Samoa'),
('Cook Islands'),
('Fiji'),
('Kiribati'),
('New Caledonia'),
('New Zealand'),
('Niue'),
('Papua New Guinea'),
('Samoa'),
('Solomon Islands'),
('Tahiti'),
('Tonga'),
('Tuvalu'),
('Vanuatu'),
('Albania'),
('Andorra'),
('Armenia'),
('Austria'),
('Azerbaijan'),
('Belarus'),
('Belgium'),
('Bosnia and Herzegovina'),
('Bulgaria'),
('Croatia'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('England'),
('Estonia'),
('Faroe Islands'),
('Finland'),
('France'),
('Georgia'),
('Germany'),
('Greece'),
('Hungary'),
('Iceland'),
('Republic of Ireland'),
('Israel'),
('Italy'),
('Kazakhstan'),
('Latvia'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('FYR Macedonia'),
('Malta'),
('Moldova'),
('Montenegro'),
('Netherlands'),
('Northern Ireland'),
('Norway'),
('Poland'),
('Portugal'),
('Romania'),
('Russia'),
('San Marino'),
('Scotland'),
('Serbia'),
('Slovakia'),
('Slovenia'),
('Spain'),
('Sweden'),
('Switzerland'),
('Turkey'),
('Ukraine'),
('Wales');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
