SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- --------------------------------------------------------

--
-- Table structure for table `ncaa_teams`
--

CREATE TABLE `ncaa_teams` (
  `name` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `ncaa_teams`
--

INSERT INTO `ncaa_teams` (`name`) VALUES
('Boston College Eagles'),
('Clemson University Tigers'),
('Duke University Blue Devils'),
('Florida State University Seminoles'),
('Georgia Institute of Technology Yellow Jackets'),
('University of Maryland, College Park Terrapins'),
('University of Miami Hurricanes'),
('University of North Carolina at Chapel Hill Tar Heels'),
('North Carolina State University Wolfpack'),
('University of Virginia Cavaliers'),
('Virginia Polytechnic Institute and State University'),
('Hokies'),
('Wake Forest University Demon Deacons'),
('University of Cincinnati Bearcats'),
('University of Connecticut Huskies'),
('DePaul University Blue Demons'),
('Georgetown University Hoyas'),
('University of Louisville Cardinals'),
('Marquette University Golden Eagles'),
('University of Notre Dame Fighting Irish'),
('University of Pittsburgh Panthers'),
('Providence College Friars'),
('Rutgers University Scarlet Knights'),
('St. John\'s University Red Storm'),
('Seton Hall University Pirates'),
('University of South Florida Bulls'),
('Syracuse University Orange'),
('Villanova University Wildcats'),
('West Virginia University Mountaineers'),
('Loyola University Maryland Greyhounds'),
('University of Illinois at Urbana–Champaign Fighting Illini'),
('Indiana University Hoosiers'),
('University of Iowa Hawkeyes'),
('University of Michigan Wolverines'),
('Michigan State University Spartans'),
('University of Minnesota, Twin Cities Golden Gophers'),
('University of Nebraska–Lincoln Cornhuskers'),
('Northwestern University Wildcats'),
('Ohio State University Buckeyes'),
('Pennsylvania State University Nittany Lions'),
('Purdue University Boilermakers'),
('University of Wisconsin–Madison Badgers'),
('Baylor University Bears'),
('Iowa State University Cyclones'),
('University of Kansas Jayhawks'),
('Kansas State University Wildcats'),
('University of Missouri Tigers'),
('University of Oklahoma Sooners'),
('Oklahoma State University Cowboys'),
('University of Texas Longhorns'),
('Texas A&M University Aggies'),
('Texas Tech University Red Raiders'),
('University of Alabama at Birmingham Blazers'),
('University of Central Florida Knights'),
('East Carolina University Pirates'),
('Marshall University Thundering Herd'),
('University of Memphis Tigers'),
('University of Southern Mississippi Golden Eagles'),
('University of Houston Cougars'),
('Rice University Owls'),
('Southern Methodist University Mustangs'),
('University of Texas at El Paso Miners'),
('Tulane University Green Wave'),
('University of Tulsa Golden Hurricane'),
('Army Black Knights'),
('Navy Midshipmen'),
('United States Air Force Academy Falcons'),
('University of Akron Zips'),
('Bowling Green State University Falcons'),
('University at Buffalo Bulls'),
('Kent State University Golden Flashes'),
('Miami University RedHawks'),
('Ohio University Bobcats'),
('Ball State University Cardinals'),
('Central Michigan University Chippewas'),
('Eastern Michigan University Eagles'),
('Northern Illinois University Huskies'),
('University of Toledo Rockets'),
('Western Michigan University Broncos'),
('Chicago State University Cougars'),
('University of Evansville Purple Aces'),
('Florida Atlantic University Owls'),
('Hartwick College Hawks'),
('University of Massachusetts Amherst Minutemen'),
('Missouri State University Bears'),
('Southern Illinois University Carbondale Salukis'),
('Temple University Owls'),
('Boise State University Broncos'),
('Colorado State University Rams'),
('University of New Mexico Lobos'),
('San Diego State University Aztecs'),
('Texas Christian University Horned Frogs'),
('University of Nevada, Las Vegas Rebels'),
('University of Wyoming Cowboys'),
('University of Arizona Wildcats'),
('Arizona State University Sun Devils'),
('University of California, Berkeley Golden Bears'),
('University of Colorado at Boulder Buffaloes'),
('University of Oregon Ducks'),
('Oregon State University Beavers'),
('Stanford University Cardinal'),
('University of California, Los Angeles Bruins'),
('University of Southern California Trojans'),
('University of Utah Utes'),
('University of Washington Huskies'),
('Washington State University Cougars'),
('California Polytechnic State University Mustangs'),
('California State University, Bakersfield Roadrunners'),
('California State University, Fullerton Titans'),
('University of California, Davis Aggies'),
('University of California, Santa Barbara Gauchos'),
('University of Florida Gators'),
('University of Georgia Bulldogs'),
('University of Kentucky Wildcats'),
('University of South Carolina Gamecocks'),
('University of Tennessee Volunteers'),
('Vanderbilt University Commodores'),
('University of Alabama Crimson Tide'),
('University of Arkansas Razorbacks'),
('Auburn University Tigers'),
('Louisiana State University Tigers'),
('Mississippi State University Bulldogs'),
('University of Mississippi Rebels'),
('University of Arkansas at Little Rock Trojans'),
('Arkansas State University Red Wolves'),
('University of Denver Pioneers'),
('Florida Atlantic University Owls'),
('Florida International University Golden Panthers'),
('University of Louisiana at Lafayette Ragin\' Cajuns'),
('University of Louisiana at Monroe Warhawks'),
('Middle Tennessee State University Blue Raiders'),
('University of North Texas Mean Green'),
('University of South Alabama Jaguars'),
('Troy University Trojans'),
('Western Kentucky University Hilltoppers'),
('California State University, Fresno Bulldogs'),
('University of Hawaii at Manoa Warriors/Rainbow Wahine'),
('University of Idaho Vandals'),
('Louisiana Tech University Bulldogs/Lady Techsters'),
('University of Nevada, Reno Wolf Pack'),
('New Mexico State University Aggies'),
('San Jose State University Spartans'),
('Utah State University Aggies'),
('Brigham Young University Cougars'),
('Dallas Baptist University Patriots'),
('University of North Dakota Fighting Sioux'),
('Northern Arizona University Lumberjacks'),
('California State University, Sacramento Hornets'),
('Southern Utah University Thunderbirds');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
